org: '1252331805'
app: upme-backend-coser
stage: prod
component: koa
name: upme-backend-coser
inputs:
  src:
    src: ./
    exclude:
      - .env
      - .idea
      - node_modules/**
  region: ap-shanghai
  runtime: Nodejs12.16
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60
    autoCreateDns: false
  isAutoCiDeploy: false
  functionConf:
    eip: false
    timeout: 2
    memorySize: 64
  layers:
    - name: '${output:${stage}:${app}:upme-backend-coser-layer.name}'
      version: '${output:${stage}:${app}:upme-backend-coser-layer.version}'
